### ISSUE TITLE
Automatically fit to the tree

### ISSUE THREAD

**Issue by Rizki36** [SanichKotikov/pinch-zoom-pan#16]
Is there any way to auto fit to the tree? 
If not, can you add this feature? 

Default
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/34688706-4373-4351-995b-6b9f5b6980e5">

Fit to the tree
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/558dd23c-66e2-4b5b-80c8-d30c9c885002">

App preview: https://pedigree-fe.vercel.app/pedigree?animalId=a5gr84s9
Source code: https://github.com/Rizki36/pedigree-fe/blob/main/src/modules/pedigree/components/main/Tree.tsx

**Comment by SanichKotikov** [comment]
Hi, you can try something like this:

```js
canvas.update({
  z: Math.min(
    rootElement.clientWidth / canvasElement.clientWidth,
    rootElement.clientHeight / canvasElement.clientHeight,
  ),
});
```

Nice design, by the way.

**Comment by Rizki36** [comment]
> Hi, you can try something like this:
> 
> ```js
> canvas.update({
>   z: Math.min(
>     rootElement.clientWidth / canvasElement.clientWidth,
>     rootElement.clientHeight / canvasElement.clientHeight,
>   ),
> });
> ```
> 
> Nice design, by the way.

Yey, its works
Thank you
