### ISSUE TITLE
Onclick focus target on canvas

### ISSUE THREAD

**Issue by msandora** [SanichKotikov/pinch-zoom-pan#3]
Hello,
I am working with this component and I was wondering if it supports the ability to focus on an element within the canvas.

For example, If I click a button I would like to change position of the canvas so that an element will be centered on the canvas. 

Please let me know if this is possible, thanks.

**Comment by SanichKotikov** [comment]
@msandora sorry for late answer :)

Starting from `v4.0.0` you can use

```js
const canvas = create({...});
canvas.update({ x, y });
```
